### ISSUE TITLE
https://felixhertlein.github.io/inv3d/#Downloads License ?

### ISSUE THREAD

**Issue by Li0ness** [FelixHertlein/inv3d-model#4]
Hi

Could you please help to understand what license covers dataset from https://felixhertlein.github.io/inv3d/#Downloads
Here https://radar.kit.edu/radar/en/dataset/JnvMMjtvIjxpUpGz 
I see CC BY-NC-SA 4.0 with some not clear note about  'restricted-license-files.txt'.
Does the file just list files under CC BY-NC-SA 4.0? or
Files from this file could be used under different terms?

**Comment by FelixHertlein** [comment]
All files are under the license CC BY-NC-SA 4.0 except for the files listed in 'restricted-license-files.txt'.
All files listed in the .txt file are only for academic use. 

Here is an excerpt of the .txt file:

> 24984/flat_document.png
> 24984/flat_document.pdf
> 24984/flat_template.png
> 24984/warped_document.png
> 24984/warped_albeldo.png

We needed to restrict the license for these files since they display a logo from the Large Logo Dataset, which is only available for academic use.

**Comment by Li0ness** [comment]
@FelixHertlein , thanks a lot for quick answer!
It's a bit curious because CC BY-NC-SA 4.0 doesn't allow commercial purposes. 
So you make limitation even stronger

**Comment by FelixHertlein** [comment]
The limitation "academic use only" is given by the Large Logo Dataset. 

We selected CC BY-NC-SA 4.0 for the rest of the files, since this allows non-academic and non-commercial entities to use our remaining data, such as non-governmental organizations for instance.
